---
 - name: using handlers
   hosts: all
   force_handlers: yes
   tasks:
     - name:
       user:
         name: user14444
         state: present
       notify: creating grp

     - name: using yum     
       yum:
         name: nope
         state: present
 
   handlers:
     - name: creating grp
       group:
         name: group301
         state: present
    
     - name:
       command: "touch /root/file111"
    



