---
 - name: creating multiplay
   hosts: ansible1.com
   tasks:
     - name: remove httpd
       yum:
         name: httpd
         state: absent

     - name: delete user
       user:
         name: kimSo
         state: absent


 - name: creating multiplay
   hosts: ansible2.com
   tasks: 
     - name: copy file and changed permission
       copy: 
         src: /home/pratibhasingh/ansible/devops
         mode: '666'
         dest: /mnt/








