---
 - name: using module group,user,yum,FILE
   hosts: all
   tasks:
     - name: create a group
       group:
         name: redhat
         state: present

     - name: create a user
       user:
         name: kimSo
         uid: '1200'
         groups: redhat
         state: present

     - name: installing webserver
       yum:
         name: httpd
         state: present
  
     - name: creating a file
       file:
         path: /mnt/test
         state: touch

     - name: adding a line
       lineinfile:
         path: /mnt/test
         line: 'this is for testing'
         create: yes
         state: present

